allowBuilds:
  '@google/genai': true
  bcrypt: true
  better-sqlite3: true
  esbuild: true
  node-pty: true
  protobufjs: true
  sharp: true
  sqlite3: true
onlyBuiltDependencies:
  - '@google/genai'
  - bcrypt
  - better-sqlite3
  - esbuild
  - node-pty
  - protobufjs
  - sharp
  - sqlite3
